### ISSUE TITLE
XCode9 compiler problem

### ISSUE THREAD

**Issue by tuzzo77** [whitesmith/MeasureThings#3]
Thanks for the code. For me in Xcode 9 not compiling:
![schermata 2017-08-24 alle 09 21 07](https://user-images.githubusercontent.com/4814593/29654456-99886bbc-88ad-11e7-95c0-92d714d93555.png)

**Comment by ricardopereira** [comment]
@tuzzo77 Xcode 9 beta 6 right? I'm aware of it. I will fix this when possible. Thanks for the issue.

**Comment by ricardopereira** [comment]
Updated https://github.com/whitesmith/MeasureThings/commit/a1383399c0ed0f251b1278e13be5be986ecae8f7
