### ISSUE TITLE
No video (black view) on iPhone 6

### ISSUE THREAD

**Issue by RegisAG** [whitesmith/MeasureThings#4]
The live video is just a clack screen on my iPhone 6. 

Anybody can help ?

Thanks !

![img_4461](https://user-images.githubusercontent.com/11994991/29915433-32b46d66-8e3c-11e7-88d0-f2dea4a31d0c.PNG)

**Comment by ricardopereira** [comment]
@RegisAG ARKit doesn't run on iPhone 6. Only for 6S and newer. Sorry.
